
ALTER TABLE public.assets
  ADD COLUMN IF NOT EXISTS current_building_coverage numeric,
  ADD COLUMN IF NOT EXISTS legal_max_building_coverage numeric,
  ADD COLUMN IF NOT EXISTS current_floor_area_ratio numeric,
  ADD COLUMN IF NOT EXISTS legal_max_floor_area_ratio numeric,
  ADD COLUMN IF NOT EXISTS current_floor_area numeric,
  ADD COLUMN IF NOT EXISTS land_value_per_sqm numeric,
  ADD COLUMN IF NOT EXISTS asset_use_type text,
  ADD COLUMN IF NOT EXISTS population_trend text,
  ADD COLUMN IF NOT EXISTS commercial_density text,
  ADD COLUMN IF NOT EXISTS distance_to_center numeric,
  ADD COLUMN IF NOT EXISTS historical_value text,
  ADD COLUMN IF NOT EXISTS natural_scenery text,
  ADD COLUMN IF NOT EXISTS building_condition text,
  ADD COLUMN IF NOT EXISTS is_private_negotiation boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_citizen_proposal boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_waterfront_environmental boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_military_heritage_zone boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_urban_facility_conflict boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS zoning_upgrade_gain text,
  ADD COLUMN IF NOT EXISTS use_change_expansion text,
  ADD COLUMN IF NOT EXISTS has_conversion_precedent boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_urban_regeneration_area boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_abandoned_school_budget boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_balanced_dev_budget boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS scoring_grade text,
  ADD COLUMN IF NOT EXISTS scoring_total numeric,
  ADD COLUMN IF NOT EXISTS scoring_detail jsonb,
  ADD COLUMN IF NOT EXISTS irr_result jsonb;
