
COMMENT ON COLUMN public.assets.id IS '자산 고유 ID';
COMMENT ON COLUMN public.assets.address IS '주소';
COMMENT ON COLUMN public.assets.asset_type IS '자산 유형 (폐교/관사/부지 등)';
COMMENT ON COLUMN public.assets.zoning IS '용도지역 (예: 일반주거)';
COMMENT ON COLUMN public.assets.building_coverage IS '건폐율 (%) — 레거시';
COMMENT ON COLUMN public.assets.floor_area_ratio IS '용적률 (%) — 레거시';
COMMENT ON COLUMN public.assets.land_area IS '대지면적 (m²)';
COMMENT ON COLUMN public.assets.idle_years IS '유휴 기간 (년)';
COMMENT ON COLUMN public.assets.ownership_type IS '소유 형태 (국유/공유/사유)';
COMMENT ON COLUMN public.assets.grade IS '등급 (레거시)';
COMMENT ON COLUMN public.assets.gov_cooperation IS '지자체 협력 가능 여부';
COMMENT ON COLUMN public.assets.latitude IS '위도';
COMMENT ON COLUMN public.assets.longitude IS '경도';
COMMENT ON COLUMN public.assets.admin_memo IS '관리자 메모';
COMMENT ON COLUMN public.assets.is_published IS '공개 여부';
COMMENT ON COLUMN public.assets.created_at IS '등록 일시';

COMMENT ON COLUMN public.assets.current_building_coverage IS '현재 건폐율 (%)';
COMMENT ON COLUMN public.assets.legal_max_building_coverage IS '법정 최대 건폐율 (%)';
COMMENT ON COLUMN public.assets.current_floor_area_ratio IS '현재 용적률 (%)';
COMMENT ON COLUMN public.assets.legal_max_floor_area_ratio IS '법정 최대 용적률 (%)';
COMMENT ON COLUMN public.assets.current_floor_area IS '현재 연면적 (m²)';
COMMENT ON COLUMN public.assets.land_value_per_sqm IS '공시지가 (원/m²)';
COMMENT ON COLUMN public.assets.asset_use_type IS '전환 용도';
COMMENT ON COLUMN public.assets.population_trend IS '인구 추세';
COMMENT ON COLUMN public.assets.commercial_density IS '상업 밀집도';
COMMENT ON COLUMN public.assets.distance_to_center IS '도심까지 거리 (km)';
COMMENT ON COLUMN public.assets.historical_value IS '역사·문화 가치';
COMMENT ON COLUMN public.assets.natural_scenery IS '자연 경관';
COMMENT ON COLUMN public.assets.building_condition IS '건물 상태';
COMMENT ON COLUMN public.assets.is_private_negotiation IS '수의계약 가능 여부';
COMMENT ON COLUMN public.assets.is_citizen_proposal IS '시민 제안 사업 여부';
COMMENT ON COLUMN public.assets.is_waterfront_environmental IS '수변·환경 규제 지역 여부';
COMMENT ON COLUMN public.assets.is_military_heritage_zone IS '군사·문화재 보호구역 여부';
COMMENT ON COLUMN public.assets.is_urban_facility_conflict IS '도시계획시설 저촉 여부';
COMMENT ON COLUMN public.assets.zoning_upgrade_gain IS '종상향 여력';
COMMENT ON COLUMN public.assets.use_change_expansion IS '용도변경 확대 가능성';
COMMENT ON COLUMN public.assets.has_conversion_precedent IS '인근 용도변경 전례 여부';
COMMENT ON COLUMN public.assets.is_urban_regeneration_area IS '도시재생기금 해당 여부';
COMMENT ON COLUMN public.assets.is_abandoned_school_budget IS '폐교 교육부 예산 해당 여부';
COMMENT ON COLUMN public.assets.is_balanced_dev_budget IS '균형발전특별회계 해당 여부';
COMMENT ON COLUMN public.assets.scoring_grade IS '종합 등급 (S/A/B/C/D, 자동 계산)';
COMMENT ON COLUMN public.assets.scoring_total IS '종합 점수 (자동 계산)';
COMMENT ON COLUMN public.assets.scoring_detail IS '블록별 점수 상세 JSON (자동 계산)';
COMMENT ON COLUMN public.assets.irr_result IS 'IRR 시나리오 결과 JSON (자동 계산)';
